#! Python3

# string analyzer to sort DNA Nucleotides



dataset = 'TTCTCAGTAACTAAGTTACGTCATGAGACGTCGCACCCACGCTGTCGACATCCGACATATTTTCAGGCCGTAATCAATGAACCGCTTTGGCTATGTGGTAGCGGCCAACACCGGATCCTTATAACAATACATCAACTAAATCTGATGGCTACCACTCTCCGGTTACTTATAGGGCCTCCCGCAAATTGGAACGTAGGCTACTAGTGTGCCCTGTAGAGTTGGTGTAGCGATTCCCAGTCGGCCTGGCAGGCCCGGCAACAGCTAATTGGTACTGGACTCACTGTACACTAGATGATGGTTATAGGGCATTAGTTGAGATCATAGGAGTCGTCGGCTAACAAGTAACGCTTCGTCCCATGAAGGGTGGTCAACTAGTACCTAGTGTTCTATTCCAATTGCCTATCAGGTCCGAATTGTATGGCAGGGTGAAACGAGTAGGTCCATAAATGTGGGTGAGGGGTATCACGTGTCCGCCGGACCTAACACAGCTGCTCCCGGGTGTTCAGATACTTATCAGTATATACCAGGGTAGTGCGACATGATGTAGTTGGCGCATTCTCCAGGAAATTGTCCACCCTTATAGGCCCACGACTTTCACCTCGTAGCGTTCCCATTACAGCGCGTGCCTAACTGGTGCTATGGATCAGATCTCTTCCTTTCATTGCACATCTGCAAACCAGCTGTCAAAGAATCCGCATGGCCGATGCATGATTGCACATTAGCATTACACGGCTGCATACGGCAGTACAGCCCTTGAAGGGGGTGGGCAATTTGTAAATTTTGGGTAGGCAGCGATAATGTTTCTTCCCGAGA'


adenine = ''
cytosine =''
guanine = ''
thymine = ''

output = ''


def adenineFunction():
	print ('\ncalculating adenine...')
	print(dataset.count('A'))

def cytosineFunction():
	print ('\ncalculating cytosine...')
	print(dataset.count('C'))

def guanineFunction():
	print ('\ncalculating guanine...')
	print(dataset.count('G'))

def thymineFunction():
	print ('\ncalculating thymine...')
	print(dataset.count('T'))

adenineFunction()
cytosineFunction()
guanineFunction()
thymineFunction()


A = dataset.count('A')
C = dataset.count('C')
G = dataset.count('G')
T = dataset.count('T')

print(str(A) + ' ' + str(C) + ' ' + str(G) + ' ' + str(T))